packages:
  - .

catalog:
  '@bufbuild/protobuf': ^2.12.1
  '@stylistic/eslint-plugin': ^5.10.0
  '@types/node': ^26.0.1
  '@typescript/native-preview': 7.0.0-dev.20260430.1
  clean-pkg-json: ^2.0.0
  eslint: ^10.3.0
  eslint-plugin-oxlint: ^1.62.0
  lint-staged: ^17.0.0
  oxfmt: ^0.56.0
  oxlint: ^1.62.0
  oxlint-tsgolint: ^0.23.0
  sort-package-json: ^4.0.0
  tsdown: ^0.22.3
  typescript: ^6.0.3
  typescript-eslint: ^8.59.1

catalogMode: strict

enablePrePostScripts: true

minimumReleaseAge: 2880

shellEmulator: true
